import numpy as np
domain_size = 500
parameters = {
    "domain_size": domain_size,
    "T": 500,
    "dt": 1,    
    "S0": 50000,
    "R0": 500,
    "N0": 0,
    "grS": 0.023,
    "grR": 0.023,
    "grN": 0.00,
    "drS": 0.01,
    "drR": 0.01,
    "drN": 0.0,
    "divrS": 0.75,
    "divrN": 0.5,
    "therapy": "adaptive",
    "initial_condition_type": "resistant_core",
    "fill_factor": 0.8,
    "core_locations": np.array([[domain_size//4,domain_size//4],[3*domain_size//4,3*domain_size//4]]),
    "save_locations": True,
    "dimension": 2,
    "diffusion_rate": 0.1,
    "seed": 0,
    "foldername": None,
    "save_frequency": 100,
}